---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache24 package
    pkgng:
      name: apache24
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: add php support for apache
    pkgng:
      name: mod_php81
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: enable apache
    service:
      name: apache24
      enabled: yes
      state: started
    when: ansible_distribution == "FreeBSD"
