---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for FreeBSD
    pkgng:
      name:
        - apache24
        - mod_php81
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: enable and start apache for FreeBSD
    service:
      name: apache24
      enabled: yes
      state: started
    when: ansible_distribution == "FreeBSD"
