---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates FreeBSD
    tags: always
    pkgng:
      name: "*"
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: install updates Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu 
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for FreeBSD
    tags: apache,apache24,freebsd
    pkgng:
      name:
        - apache24
        - mod_php81
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: enable and start apache for FreeBSD
    tags: apache,apache24,freebsd
    service:
      name: apache24
      enabled: yes
      state: started
    when: ansible_distribution == "FreeBSD"

  - name: copy default html file for site
    tags: apache,apache2,apache24
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package for Ubuntu
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb package for Freebsd
      tags: freebsd,db,mariadb
      pkgng:
        name: mariadb106-server
        state: latest
      when: ansible_distribution == "FreeBSD"

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      tags: fileserver,samba
      package:
        name: samba
        state: latest
