---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates FreeBSD
    pkgng:
      name: "*"
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: install updates Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for FreeBSD
    pkgng:
      name:
        - apache24
        - mod_php81
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: enable and start apache for FreeBSD
    service:
      name: apache24
      enabled: yes
      state: started
    when: ansible_distribution == "FreeBSD"

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package for Ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb package for Freebsd
      pkgng:
        name: mariadb106-server
        state: latest
      when: ansible_distribution == "FreeBSD"

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      package:
        name: samba
        state: latest
